# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "b007d985e2197246e9e060f6ce67e35f"
name = "columbia-gift-product"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true
handle = "columbia-gift-product"

[build]
include_config_on_deploy = true

[webhooks]
api_version = "2025-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_payment_customizations"

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[pos]
embedded = false
